config/routes.rb
AirportTransfers::Application.routes.draw do

  resources :bookings
  get '/booking_:airport_id' => 'bookings#new', as: 'booking_airport'
  get '/dest_:airport' => 'bookings#book_dest', as: 'book_dest'
  match '/vehicletypes_booking_:passangers&:baggages&:from&:to', to: 'vehicletypes#vehicletypes_booking', via: 'get', as: 'vehicletypes_for_booking'


  resources :destination_fares

  resources :destinations
  match '/destination_booking', to: 'destinations#booking', via: 'get', as: 'destination_for_booking'

  resources :suppliers

  resources :airports
  resources :airports do
    collection { post :import }
  end
  match '/import_airports_form', to: 'airports#import_form', via: 'get', as: 'import_airports_form'

  resources :vehicletypes

  resources :reviews
  match '/all_reviews', to: 'reviews#index_site', via: 'get'

  resources :password_resets

  # OAuth
  match 'auth/:provider/callback', to: 'sessions#create_oauth', via: [:get, :post]
  # OAuth with token
  match 'auth/:provider/:invitation_token', to: 'sessions#create_oauth_with_token', via: [:get, :post]

  #match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'auth/failure', to: 'sessions#fail_oauth', via: [:get, :post]
  match 'signout', to: 'sessions#destroy_oauth', as: 'signout', via: [:get, :post]

  resources :blogs
  match '/create_blog', to: 'blogs#new', via: 'get'
  match '/all_blogs', to: 'blogs#index_site', via: 'get'


  resources :orders, only: [:index, :create, :new]
  match '/payment', to: 'orders#payment', via: 'get'

  # Payment status return
  match '/pay_status_paypal', to: 'orders#pay_status_paypal', via: 'get'

  resources :transactions, only: [:index, :create, :new]

  match '/access_deny', to: 'static_pages#access_deny', via: 'get'

  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/unsubscribe', to: 'users#unsubscribe', via: 'get'
  match '/unsubscribe_action', to: 'users#unsubscribe_action', via: 'post'

  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signup/:invitation_token', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/countries', to: 'static_pages#countries', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/partners', to: 'static_pages#partners', via: 'get'
  match '/transfers', to: 'static_pages#transfers', via: 'get'

end

app/controllers/vehicletypes_controller.rb
class VehicletypesController < ApplicationController
  before_action :set_vehicletype, only: [:show, :edit, :update, :destroy]

  # Check user role
  before_action :check_role_client, only: [:index, :new, :show, :edit, :create, :update, :destroy]
  before_action :check_role_partner, only: [:index, :new, :show, :edit, :create, :update, :destroy]

  # GET /vehicletypes
  # GET /vehicletypes.json
  def index
    @vehicletypes = Vehicletype.paginate(page: params[:page])
  end

  def vehicletypes_booking
    @vehicletypes = Vehicletype.all
    respond_to do |format|
        format.js
    end
  end

  # GET /vehicletypes/1
  # GET /vehicletypes/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /vehicletypes/new
  def new
    @vehicletype = Vehicletype.new
  end

  # GET /vehicletypes/1/edit
  def edit
  end

  # POST /vehicletypes
  # POST /vehicletypes.json
  def create
    @vehicletype = Vehicletype.new(vehicletype_params)

    respond_to do |format|
      if @vehicletype.save
        format.html { redirect_to @vehicletype, notice: 'Vehicletype was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vehicletype }
      else
        format.html { render action: 'new' }
        format.json { render json: @vehicletype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicletypes/1
  # PATCH/PUT /vehicletypes/1.json
  def update
    respond_to do |format|
      if @vehicletype.update(vehicletype_params)
        format.html { redirect_to @vehicletype, notice: 'Vehicletype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vehicletype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicletypes/1
  # DELETE /vehicletypes/1.json
  def destroy
    @vehicletype.destroy
    respond_to do |format|
      format.html { redirect_to vehicletypes_url }
      format.json { head :no_content }
    end
  end

  # Check user role
  def check_role_client
    if (current_user && current_user.role == "Client") || (current_user && current_user.role == "OAuth")
      redirect_to root_path
      flash[:danger] = I18n.t 'flash.access_deny_text'
    end
  end

  def check_role_partner
    if (current_user && current_user.role == "Partner") || (current_user && current_user.role == "OAuth")
      redirect_to root_path
      flash[:danger] = I18n.t 'flash.access_deny_text'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicletype
      @vehicletype = Vehicletype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicletype_params
      params.require(:vehicletype).permit(:vtype, :vdescription, :image, :passnum, :bagagenum)
    end
end

app/helpers/vehicletypes_helper.rb
module VehicletypesHelper
end

app/views/vehicletypes/_form.html.erb
<%= form_for(@vehicletype) do |f| %>
  <% if @vehicletype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicletype.errors.count, "error") %> prohibited this vehicletype from being saved:</h2>

      <ul>
      <% @vehicletype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vtype %><br>
    <%= f.text_field :vtype %>
  </div>
  <div class="field">
    <%= f.label :vdescription %><br>
    <%= f.text_field :vdescription %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :passnum %><br>
    <%= f.number_field :passnum %>
  </div>
  <div class="field">
    <%= f.label :bagagenum %><br>
    <%= f.number_field :bagagenum %>
  </div>
  <div class="actions">
    <%= f.submit (t 'button.ok'), class: "btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/vehicletypes/_show.html.erb
<div class="portrait_map">
  <img alt="" src="<%= @vehicletype.image %>">
</div>
<p>
  <b>Type: </b><%= @vehicletype.vtype %>
</p>

app/views/vehicletypes/edit.html.erb
<h1 align="center">Editing vehicletype</h1>

<%= render 'form' %>

<%= link_to (I18n.t 'button.show'), @vehicletype, class: "btn btn-sm btn-primary" %> |
<%= link_to (I18n.t 'button.back'), vehicletypes_path, class: "btn btn-sm btn-warning" %>

app/views/vehicletypes/index.html.erb
<h1 align="center">Listing vehicletypes <span class="badge"><%= @vehicletypes.count %></span></h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Vtype</th>
      <th>Vdescription</th>
      <th>Image</th>
      <th>Passnum</th>
      <th>Bagagenum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicletypes.each do |vehicletype| %>
      <tr>
        <td><%= vehicletype.vtype %></td>
        <td><%= vehicletype.vdescription %></td>
        <td><div class="portrait_map">
          <img alt="" src="<%= vehicletype.image %>">
        </div></td>
        <td><%= vehicletype.passnum %></td>
        <td><%= vehicletype.bagagenum %></td>
        <td><%= link_to (I18n.t 'button.show'), vehicletype, class: "btn btn-sm btn-primary" %></td>
        <td><%= link_to (I18n.t 'button.edit'), edit_vehicletype_path(vehicletype), class: "btn btn-sm btn-warning" %></td>
        <td><%= link_to (I18n.t 'button.delete'), vehicletype, method: :delete, data: {confirm: (t 'operations_confirmation.confirm')}, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicletype', new_vehicletype_path, class: "btn btn-sm btn-primary" %>

app/views/vehicletypes/new.html.erb
<h1 align="center">New vehicletype</h1>

<%= render 'form' %>

<%= link_to (I18n.t 'button.back'), vehicletypes_path, class: "btn btn-sm btn-warning" %>

app/views/vehicletypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vtype:</strong>
  <%= @vehicletype.vtype %>
</p>

<p>
  <strong>Vdescription:</strong>
  <%= @vehicletype.vdescription %>
</p>

<p>
  <strong>Image:</strong>
<div class="portrait_map">
  <img alt="" src="<%= @vehicletype.image %>">
</div>
</p>

<p>
  <strong>Passnum:</strong>
  <%= @vehicletype.passnum %>
</p>

<p>
  <strong>Bagagenum:</strong>
  <%= @vehicletype.bagagenum %>
</p>

<%= link_to (I18n.t 'button.edit'), edit_vehicletype_path(@vehicletype), class: "btn btn-sm btn-primary" %> |
<%= link_to (I18n.t 'button.back'), vehicletypes_path, class: "btn btn-sm btn-warning" %>

app/views/vehicletypes/show.js.erb
$('#vehicletype_booking_info').append('<div id="vehicletype_booking_information"><%= j render("vehicletypes/show") %></div>');

app/views/vehicletypes/vehicletypes_booking.js.erb
$('#destination').append('<div id="destination_result"><%= j render("bookings/step_2") %></div>');