config/routes.rb
AirportTransfers::Application.routes.draw do

  resources :bookings
  get '/booking_:airport_id' => 'bookings#new', as: 'booking_airport'
  get '/dest_:airport' => 'bookings#book_dest', as: 'book_dest'
  match '/vehicletypes_booking_:passangers&:baggages&:from&:to', to: 'vehicletypes#vehicletypes_booking', via: 'get', as: 'vehicletypes_for_booking'


  resources :destination_fares

  resources :destinations
  match '/destination_booking', to: 'destinations#booking', via: 'get', as: 'destination_for_booking'

  resources :suppliers

  resources :airports
  resources :airports do
    collection { post :import }
  end
  match '/import_airports_form', to: 'airports#import_form', via: 'get', as: 'import_airports_form'

  resources :vehicletypes

  resources :reviews
  match '/all_reviews', to: 'reviews#index_site', via: 'get'

  resources :password_resets

  # OAuth
  match 'auth/:provider/callback', to: 'sessions#create_oauth', via: [:get, :post]
  # OAuth with token
  match 'auth/:provider/:invitation_token', to: 'sessions#create_oauth_with_token', via: [:get, :post]

  #match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'auth/failure', to: 'sessions#fail_oauth', via: [:get, :post]
  match 'signout', to: 'sessions#destroy_oauth', as: 'signout', via: [:get, :post]

  resources :blogs
  match '/create_blog', to: 'blogs#new', via: 'get'
  match '/all_blogs', to: 'blogs#index_site', via: 'get'


  resources :orders, only: [:index, :create, :new]
  match '/payment', to: 'orders#payment', via: 'get'

  # Payment status return
  match '/pay_status_paypal', to: 'orders#pay_status_paypal', via: 'get'

  resources :transactions, only: [:index, :create, :new]

  match '/access_deny', to: 'static_pages#access_deny', via: 'get'

  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/unsubscribe', to: 'users#unsubscribe', via: 'get'
  match '/unsubscribe_action', to: 'users#unsubscribe_action', via: 'post'

  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signup/:invitation_token', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/countries', to: 'static_pages#countries', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/partners', to: 'static_pages#partners', via: 'get'
  match '/transfers', to: 'static_pages#transfers', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :supplier
  has_many :orders
  has_many :transactions
  has_many :bookings

  #default_scope -> { order('created_at DESC') }
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: {minimum: 2, maximum: 30}
  # E-mail Validation
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: {case_sensitive: false}
  # Password Validation
  has_secure_password
  validates :password, length: {minimum: 6}
  # Phone Validation
  #VALID_PHONE_REGEX = /([0-9]{9,10})/
  VALID_PHONE_REGEX = /([0-9]{9,10})\z/
  validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }, length: { maximum: 10 }
  validates :role, :inclusion => { :in => ['Client', 'Partner', 'OAuth'] }

  # Current user enable in model
  def self.current
    Thread.current[:user]
  end
  def self.current=(user)
    Thread.current[:user] = user
  end
  # Current user enable in model

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  # Password Reset
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(:validate => false)
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  # Password Reset

  #OAuth
  require 'securerandom'
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      @pass = SecureRandom.hex(12)
      user.password = @pass
      user.password_confirmation = @pass
      if (user.role == "Client") || (user.admin == true) || (user.role == "Partner")
      else
        user.role = "OAuth"
        user.phone = "3334444333"
        user.countrycode = "+1"
        user.subscription = true
      end
      user.oauth_token = auth.credentials.token
      user.oauth_link_image = auth.info.image
      if auth.provider == "twitter"
        user.email = auth.info.nickname + "@twitter.com"
        user.oauth_link = auth.info.urls.Twitter
      elsif auth.provider == "facebook"
        user.oauth_link = auth.info.urls.Facebook
        if auth.info.email.nil? || auth.info.email.blank?
          user.email = auth.info.nickname + "@facebook.com"
        else
          user.email = auth.info.email
        end
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      elsif auth.provider == "google_oauth2"
        user.oauth_link = auth.extra.raw_info.profile
        user.email = auth.info.email
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      else
        user.email = auth.info.email
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      end
      # check validation
      @array_error_oauth = Array.new([])
      if user.valid? && User.find_by(email: auth.info.email) == nil
        user.save!
      else
        #@user_oauth_errors = user.errors
        @array_error_oauth.push(user.errors)
      end
      #  user.save!
    end
  end

  def self.check_oauth_errors
    if @array_error_oauth.blank?
      true
    else
      false
      @array_error_oauth
    end
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :signed_in_user,
                only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :check_user, only: [:create, :new]
  before_action :check_admin, only: [:collaboration]

  # Check user role
  before_action :check_role_client, only: [:index, :destroy]
  before_action :check_role_partner, only: [:index, :destroy]

  def index
    @users = User.paginate(page: params[:page]).order(sort_column + ' ' + sort_direction)
  end

  def show
    @user = User.find(params[:id])
    @company_name_for_show = nil
    if @user.admin?
      @company_name = "Administrator"
    else
      @company_name = ""
    end
  end

  def new
    if params[:invitation_token].nil? || params[:invitation_token].blank?
      @user = User.new
    else
      @user = User.new(:invitation_token => params[:invitation_token])
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.update_attribute :subscription, true
        # Mail to user
        UserMailer.welcome_email(@user).deliver

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.js   {}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = I18n.t 'flash.profile_updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  # Check user role
  def check_role_client
    if (current_user && current_user.role == "Client") || (current_user && current_user.role == "OAuth")
      redirect_to root_path
      flash[:danger] = I18n.t 'flash.access_deny_text'
    end
  end

  def check_role_partner
    if (current_user && current_user.role == "Partner") || (current_user && current_user.role == "OAuth")
      redirect_to root_path
      flash[:danger] = I18n.t 'flash.access_deny_text'
    end
  end

  # Check user role
  def check_user
    if current_user
      redirect_to root_path
    end
  end

  def check_admin
    if current_user && current_user.admin?
      redirect_to root_path
      flash[:danger] = I18n.t 'flash.access_deny_text'
    end
  end

  def collaboration
  end

  def unsubscribe
  end
  #unsubscribe
  def unsubscribe_action
    user = User.find_by_email(params[:email])
    if user.nil?
      redirect_to root_url
      flash[:danger] = I18n.t 'unsubscribe_block.unsubscribe_error'
    else
      user.update_attribute :subscription, false
      redirect_to root_url
      flash[:success] = I18n.t 'unsubscribe_block.unsubscribe_success'
    end
  end

  private
  # Save information in database - PRIVAT
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :countrycode, :phone, :role, :terms_of_service, :invitation_token, :subscription)
  end

  # Before filters

  def correct_user
    @user = User.find(params[:id])
    if current_user.admin?
    else
      redirect_to(root_url) unless current_user?(@user)
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  # Sortable for index inquiry and settlements
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    #image_tag(gravatar_url, alt: user.name, class: "gravatar")
    image_tag(gravatar_url, alt: user.name, class: "img-circle")
  end
end

app/views/users/_new.html.erb
<script>
    $(document).ready(function () {
        $('#new_user').validate({
            validClass: "valid",
            errorClass: "error",
            success: function(label) {
                label.addClass("valid").text("Ok!")
            },
            //submitHandler: function() { $('#new_user').submit(); },
            rules: {
                'user[name]': {required: true, minlength: 2, maxlength: 30},
                'user[email]': {required: true, email: true},
                'user[phone]': {required: true, minlength: 9, maxlength: 10, digits: true}
            }
        });
    });
</script>

<div class="row" style="margin-right: 0px; margin-left: 0px;">
  <div class="col-md-12">

    <div class="well">
    <%= form_for(@user, remote: true, :url => { :controller => 'users', :action => 'create' }) do |u| %>
        <%= render 'shared/error_messages', object: u.object %>

        <%= u.label (t :name) %>
        <%= u.text_field :name %>

        <%= u.label (t :email) %>
        <%= u.text_field :email %>

          <% require 'securerandom' %>
          <% @pass = SecureRandom.hex(4) %>
          <%= u.hidden_field :password, :value => @pass %>
          <%= u.hidden_field :password_confirmation, :value => @pass %>

          <div class="row">
            <div class="col-md-6">
              <!--Save data in database use option-->
              <%= u.label (t :countrycode) %>
              <%= u.select :countrycode, options_for_select(Country.correct_country, selected: :option) %>
            </div>
            <div class="col-md-6">
              <%= u.label (t :phone) %>
              <%= u.text_field :phone, class: "form-control" %>
            </div>
          </div>
          <%= u.hidden_field :role, :value => "Client" %>
          <%= u.hidden_field :invitation_token %>

        <%= u.submit (t :create_my_account), class: "btn btn-sm btn-primary", remote: true  %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <!--GRAVATAR FOR USER-->
  <!--<%= gravatar_for user, size: 52 %>-->
  <!--<%= link_to user.name, user %>-->
  <%= link_to user.email, user %>
  <!--User created date-->
  <%= link_to user.created_at, user %>
  <!--Show user Role-->
  <%= link_to user.role, user %>
  <!--Show user CountryCode-->
  <%= link_to user.countrycode, user %><!--Show user Phone--><%= link_to user.phone, user %>
  <!--Edit User-->
  | <%= link_to (I18n.t 'button.edit'), edit_user_path(user) %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to (I18n.t 'button.delete'), user, method: :delete,
                    data: {confirm: "You sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1 align="center"><%= t :update_your_profile %></h1>

<div class="row">

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
      <div class="col-md-3 col-md-offset-1" align="center">
        <%= gravatar_for @user %>
        <p ><a href="http://gravatar.com/emails" target="_blank"><button type="button" class="btn btn-primary btn-xs"><%= t ('button.change') %></button></a></p>
        <div class="row">
          <div class="col-md-1" align="center">
            <%= f.check_box :subscription %>
          </div>
          <div class="col-md-9">
            <b><%= t :email %> </b> <%= f.label (t 'unsubscribe_block.subscription') %>
          </div>
        </div>
        </div>
      <div class="col-md-6 col-md-offset-1">
        <div class="form-group">
          <%= f.label (t :name) %>
          <%= f.text_field :name %>
        </div>

        <%= f.label (t :email) %>
        <%= f.text_field :email %>

        <%= f.label (t :password) %>
        <%= f.password_field :password %>

        <!--<%= f.label :password_confirmation, "Confirm Password" %>-->
        <%= f.label (t :password_confirmation) %>
        <%= f.password_field :password_confirmation %>

        <div class="row">
          <div class="col-md-6">
            <!--Save data in database use option-->
            <%= f.label (t :countrycode) %>
            <%= f.select :countrycode, options_for_select(Country.correct_country, selected: :option, :selected => current_user.countrycode) %>
          </div>
          <div class="col-md-6">
            <%= f.label (t :phone) %>
            <%= f.text_field :phone, class: "form-control" %>
          </div>
        </div>



        <p align="center"><%= f.submit (t :save_changes), class: "btn btn-sm btn-primary" %></p>
      </div>
    <% end %>

</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1 align="center"><%= t 'menu.users' %> <span class="badge"><%= @users.count %></span></h1>
<% if current_user.try(:admin?) %>

    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th><%= 'Avatar' %></th>
        <th><%= sortable "name", (t :name) %></th>
        <th><%= sortable "e-mail", (t :email) %></th>
        <th><%= sortable "created_at", (t :created_at) %></th>
        <th><%= sortable "role", (t :user_role) %></th>
        <th><%= sortable "provider", (t :provider) %></th>
        <th><%= (t :phone) %></th>
        <th><%= (t 'last_seen_at') %></th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <div align="center">
        <%= will_paginate %>
      </div>

      <tbody>
      <% @users.each do |user| %>
          <tr>
            <% if (user.provider == "facebook") || (user.provider == "twitter") || (user.provider == "google_oauth2") %>
                <td><%= image_tag user.oauth_link_image, class: "img-circle" %></td>
            <% else %>
                <td><%= gravatar_for user %></td>
            <% end %>
            <td><%= user.name %></td>
            <td>
              <%= user.email %>
              <%= user.oauth_link %>
            </td>
            <td><%= user.created_at %></td>
            <td>
              <% if user.admin? %>
                  <%= "Adminisrator" %>
              <% else %>
                  <%= user.role %>
              <% end %></td>
            <td><%= user.provider %></td>
            <td><%= user.countrycode %><%= user.phone %></td>
            <td><%= user.last_seen_at %></td>
            <td><%= link_to (I18n.t 'button.show'), user, class: "btn btn-sm btn-primary" %></td>
            <td><%= link_to (I18n.t 'button.edit'), edit_user_path(user), class: "btn btn-sm btn-warning" %></td>
            <td><%= link_to (I18n.t 'button.delete'), user, method: :delete,
                            data: {confirm: (t 'operations_confirmation.confirm')}, class: "btn btn-sm btn-danger" %></td>
          </tr>
      <% end %>

      </tbody>
    </table>
<% else %>
<% end %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 align="center"><%= t :sign_up %>! <%= t ('main_page.its_free') %></h1>

<script>
    $(document).ready(function () {
        $('#new_user').validate({
            validClass: "valid",
            errorClass: "error",
            success: function(label) {
                label.addClass("valid").text("Ok!")
            },
            //submitHandler: function() { $('#new_user').submit(); },
            rules: {
                'user[name]': {required: true, minlength: 2, maxlength: 30},
                'user[email]': {required: true, email: true},
                'user[password]': {required: true, minlength: 6},
                'user[password_confirmation]': {required: true, equalTo: '#user_password'},
                'user[phone]': {required: true, minlength: 9, maxlength: 10, digits: true},
                'user[terms_of_service]': {required: true}
            }
        });
    });
</script>

<div class="row" style="margin-right: 0px; margin-left: 0px;">
  <div class="col-md-6 col-md-offset-3">

    <div class="well">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label (t :name) %>
        <%= f.text_field :name %>

        <%= f.label (t :email) %>
        <%= f.text_field :email %>

        <%= f.label (t :password) %>
        <%= f.password_field :password %>

        <!--<%= f.label :password_confirmation, "Confirmation" %>-->
        <%= f.label (t :password_confirmation) %>
        <%= f.password_field :password_confirmation %>

          <div class="row">
            <div class="col-md-6">
              <!--Save data in database use option-->
              <%= f.label (t :countrycode) %>
              <%= f.select :countrycode, options_for_select(Country.correct_country, selected: :option) %>
            </div>
            <div class="col-md-6">
              <%= f.label (t :phone) %>
              <%= f.text_field :phone, class: "form-control" %>
            </div>
          </div>
        <%= f.label (t :company_type) %>
            <%= f.select :role, options_for_select([[(t 'role.client'), "Client"], [(t 'role.partner'), "Partner"]], selected: :option, :selected => @user.role) %>
          <%= f.hidden_field :invitation_token %>
        <!--Terms of use and Privacy and security-->
        <div class="row">
          <div class="col-md-1"><%= f.check_box :terms_of_service %></div>
          <div class="col-md-11">
            <%= link_to(t("menu.terms"), terms_path, :target => "_blank") %>
          </div>
        </div>
        </br>

        <%= f.submit (t :create_my_account), class: "btn btn-sm btn-primary" %>
    <% end %>
    </div>
  </div>
  <!-- OAuth login -->
  <div class="col-md-2">
    <div class="well" style="padding-right: 240px;">
    <strong><%= t ('or') %></strong>
    <div class="btn-group-vertical">
      <% if params[:invitation_token].nil? || params[:invitation_token].blank? %>
          <%= link_to ("/auth/facebook") do %>
              <button type="button" class="btn btn-default" style="width: 220px;"><%= image_tag("facebook-black@2x.png") %> <%= (t 'Sign in with Facebook') %></button>
          <% end %>
          <%= link_to ("/auth/twitter") do %>
              <button type="button" class="btn btn-default" style="width: 220px;"><%= image_tag("twitter-black@2x.png") %> <%= (t 'Sign in with Twitter') %></button>
          <% end %>
          <%= link_to ("/auth/google_oauth2") do %>
              <button type="button" class="btn btn-default" style="width: 220px;"><%= image_tag("google-plus-black@2x.png") %> <%= (t 'Sign in with Google') %></button>
          <% end %>
      <% else %>
          <%= link_to ("/auth/facebook/" + params[:invitation_token]) do %>
              <button type="button" class="btn btn-default" style="width: 220px;"><%= image_tag("facebook-black@2x.png") %> <%= (t 'Sign in with Facebook') %></button>
          <% end %>
          <%= link_to ("/auth/twitter/" + params[:invitation_token]) do %>
              <button type="button" class="btn btn-default" style="width: 220px;"><%= image_tag("twitter-black@2x.png") %> <%= (t 'Sign in with Twitter') %></button>
          <% end %>
          <%= link_to ("/auth/google_oauth2/" + params[:invitation_token]) do %>
              <button type="button" class="btn btn-default" style="width: 220px;"><%= image_tag("google-plus-black@2x.png") %> <%= (t 'Sign in with Google') %></button>
          <% end %>
      <% end %>
    </div>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-12">
    <section>
      <h1><%= @user.email %></h1>
          <ul class="listylenone">
            <% if current_user && current_user.admin? %>
                <% if (@user.provider == "facebook") || (@user.provider == "twitter") || (@user.provider == "google_oauth2") %>
                    <li><%= image_tag @user.oauth_link_image, class: "img-circle" %></li>
                <% else %>
                    <li><%= gravatar_for @user %></li>
                <% end %>
            <% end %>
            <li><b><%= t :name %>:</b> <%= @user.name %></li>
            <li><b><%= t :email %>:</b> <%= @user.email %></li>
            <!--User created date-->
            <li><b><%= t :created_at %>:</b> <%= @user.created_at %></li>
            <!--Show user CountryCode-->
            <li><b><%= t :phone %>:</b> <%= @user.countrycode %><!--Show user Phone--><%= @user.phone %></li>
            <!--Show user Role-->
            <li><b><%= t :company_type %>:</b> <%= @user.role %></li>
            <li><b><%= t :company_name %>:</b> <%= @company_name %><%= @company_name_for_show %></li>
            <% if current_user && current_user.admin? %>
                <li><b><%= t (t 'last_seen_at') %>:</b> <%= @user.last_seen_at %></li>
                <li><b><%= t :provider %>:</b> <%= @user.provider %></li>
                <li><b><%= t :oauth_link %>:</b> <%= @user.oauth_link %></li>
                <li><b><%= t :invitation_token %>:</b> <%= @user.invitation_token %></li>
                <li><b><%= t ('unsubscribe_block.subscription') %>:</b> <%= @user.subscription %></li>
            <% end %>
          </ul>

      <!--Edit User-->

    </section>

  </aside>

</div>

app/views/users/unsubscribe.html.erb
<h1 align="center"><%= t ('unsubscribe_block.unsubscribe') %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_tag unsubscribe_action_path, :method => :post do %>
        <p align="center"><%= t ('unsubscribe_block.enter_email') %></p>
    <div class="field">
      <%= label_tag (t :email) %>
      <%= text_field_tag :email, params[:email] %>
    </div>
    <div class="actions"><%= submit_tag (I18n.t 'unsubscribe_block.unsubscribe'), class: "btn btn-sm btn-primary" %></div>
<% end %>
  </div>
</div>