config/routes.rb
AirportTransfers::Application.routes.draw do

  resources :bookings
  get '/booking_:airport_id' => 'bookings#new', as: 'booking_airport'
  get '/dest_:airport' => 'bookings#book_dest', as: 'book_dest'
  match '/vehicletypes_booking_:passangers&:baggages&:from&:to', to: 'vehicletypes#vehicletypes_booking', via: 'get', as: 'vehicletypes_for_booking'


  resources :destination_fares

  resources :destinations
  match '/destination_booking', to: 'destinations#booking', via: 'get', as: 'destination_for_booking'

  resources :suppliers

  resources :airports
  resources :airports do
    collection { post :import }
  end
  match '/import_airports_form', to: 'airports#import_form', via: 'get', as: 'import_airports_form'

  resources :vehicletypes

  resources :reviews
  match '/all_reviews', to: 'reviews#index_site', via: 'get'

  resources :password_resets

  # OAuth
  match 'auth/:provider/callback', to: 'sessions#create_oauth', via: [:get, :post]
  # OAuth with token
  match 'auth/:provider/:invitation_token', to: 'sessions#create_oauth_with_token', via: [:get, :post]

  #match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'auth/failure', to: 'sessions#fail_oauth', via: [:get, :post]
  match 'signout', to: 'sessions#destroy_oauth', as: 'signout', via: [:get, :post]

  resources :blogs
  match '/create_blog', to: 'blogs#new', via: 'get'
  match '/all_blogs', to: 'blogs#index_site', via: 'get'


  resources :orders, only: [:index, :create, :new]
  match '/payment', to: 'orders#payment', via: 'get'

  # Payment status return
  match '/pay_status_paypal', to: 'orders#pay_status_paypal', via: 'get'

  resources :transactions, only: [:index, :create, :new]

  match '/access_deny', to: 'static_pages#access_deny', via: 'get'

  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/unsubscribe', to: 'users#unsubscribe', via: 'get'
  match '/unsubscribe_action', to: 'users#unsubscribe_action', via: 'post'

  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signup/:invitation_token', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/countries', to: 'static_pages#countries', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/partners', to: 'static_pages#partners', via: 'get'
  match '/transfers', to: 'static_pages#transfers', via: 'get'

end

app/views/layouts/menu/_sidebar.html.erb
<!--Sidebar left-->
<div class="span3 bs-docs-sidebar">
  <ul class="nav nav-list bs-docs-sidenav affix">
    <!--Admin user menu-->
    <% if current_user.try(:admin?) %>
        <%= render 'layouts/menu/sidebar_menu_admin' %>
    <% elsif current_user && current_user.role == "Partner" %>
        <%= render 'layouts/menu/sidebar_menu_partner' %>
    <% elsif current_user && current_user.role == "Client" %>
        <%= render 'layouts/menu/sidebar_menu_client' %>
    <% else %>
    <% end %>
  </ul>
    </div>

app/views/layouts/menu/_sidebar_menu_admin.html.erb
<li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/adress-book3-black@2x.png') +' '+ (I18n.t 'booking.new'), new_booking_path %></li>
<li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/calendar-black@2x.png') +' '+ (I18n.t 'booking.bookings'), bookings_path %></li>
<li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/earth-black@2x.png') +' '+ (I18n.t 'menu.countries_list'), countries_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/user-black@2x.png') +' '+  (I18n.t 'menu.users'), users_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/notepad2-black@2x.png') +' '+  (I18n.t 'blog.blogs'), blogs_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/like-black@2x.png') +' '+  (I18n.t 'review.reviews'), reviews_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/car-black@2x.png') +' '+  (I18n.t 'vehicletypes.vehicletypes'), vehicletypes_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/airplane-black@2x.png') +' '+  (I18n.t 'airports.airports'), airports_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/adress-book2-black@2x.png') +' '+  (I18n.t 'suppliers.suppliers'), suppliers_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/compass-black@2x.png') +' '+  (I18n.t 'destinations.destinations'), destinations_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/cash-black@2x.png') +' '+  (I18n.t 'destination_fares.destination_fares'), destination_fares_path %></li>
      <li class="menu_border"><%= link_to image_tag('/assets/theme/menu_icons_pack/calculator-black@2x.png') +' '+ (I18n.t 'orders.orders'), orders_path %></li>

app/views/layouts/menu/_sidebar_menu_client.html.erb
<!-- https://github.com/onokumus/metisMenu -->
<aside class="sidebar">
  <nav class="sidebar-nav">
    <ul id="menu">
      <li><%= link_to (I18n.t 'menu.home'), root_path %></li>
      <li><%= link_to (I18n.t 'menu_agent.my_orders'), root_path %></li>
      <li><%= link_to (I18n.t 'log_out'), signout_path, method: "delete" %></li>
    </ul>
  </nav>
</aside>

app/views/layouts/menu/_sidebar_menu_partner.html.erb
<!-- https://github.com/onokumus/metisMenu -->
<aside class="sidebar">
  <nav class="sidebar-nav">
    <ul id="menu">
      <li><%= link_to (I18n.t 'menu.home'), root_path %></li>
      <li><%= link_to (I18n.t 'menu_agent.my_orders'), root_path %></li>
      <li><%= link_to (I18n.t 'log_out'), signout_path, method: "delete" %></li>
    </ul>
  </nav>
</aside>