config/routes.rb
AirportTransfers::Application.routes.draw do

  resources :bookings
  get '/booking_:airport_id' => 'bookings#new', as: 'booking_airport'
  get '/dest_:airport' => 'bookings#book_dest', as: 'book_dest'
  match '/vehicletypes_booking_:passangers&:baggages&:from&:to', to: 'vehicletypes#vehicletypes_booking', via: 'get', as: 'vehicletypes_for_booking'


  resources :destination_fares

  resources :destinations
  match '/destination_booking', to: 'destinations#booking', via: 'get', as: 'destination_for_booking'

  resources :suppliers

  resources :airports
  resources :airports do
    collection { post :import }
  end
  match '/import_airports_form', to: 'airports#import_form', via: 'get', as: 'import_airports_form'

  resources :vehicletypes

  resources :reviews
  match '/all_reviews', to: 'reviews#index_site', via: 'get'

  resources :password_resets

  # OAuth
  match 'auth/:provider/callback', to: 'sessions#create_oauth', via: [:get, :post]
  # OAuth with token
  match 'auth/:provider/:invitation_token', to: 'sessions#create_oauth_with_token', via: [:get, :post]

  #match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'auth/failure', to: 'sessions#fail_oauth', via: [:get, :post]
  match 'signout', to: 'sessions#destroy_oauth', as: 'signout', via: [:get, :post]

  resources :blogs
  match '/create_blog', to: 'blogs#new', via: 'get'
  match '/all_blogs', to: 'blogs#index_site', via: 'get'


  resources :orders, only: [:index, :create, :new]
  match '/payment', to: 'orders#payment', via: 'get'

  # Payment status return
  match '/pay_status_paypal', to: 'orders#pay_status_paypal', via: 'get'

  resources :transactions, only: [:index, :create, :new]

  match '/access_deny', to: 'static_pages#access_deny', via: 'get'

  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/unsubscribe', to: 'users#unsubscribe', via: 'get'
  match '/unsubscribe_action', to: 'users#unsubscribe_action', via: 'post'

  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signup/:invitation_token', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/countries', to: 'static_pages#countries', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/partners', to: 'static_pages#partners', via: 'get'
  match '/transfers', to: 'static_pages#transfers', via: 'get'

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :destinations, :dependent => :destroy
  has_many :bookings

  validates :code, presence: true
  validates :name, presence: true
  validates :fixed_fare, presence: true


  def self.import(file)
    @array_error = Array.new([])
    #allowed_attributes = [ "id","created_at","updated_at"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      #product = find_by_id(row["id"]) || new
      product = new
      row["id"] = nil
      row["code"] = (row["name"]).last(3)
      row["fixed_fare"] = 1
      row["created_at"] = nil
      row["updated_at"] = nil
      product.attributes = row.to_hash
      #product.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
      #product.save!
      if product.valid?
        product.save!
      else
        case File.extname(file.original_filename)
          when ".csv" then
            @array_error.push(product)
          when ".xls" then
            @array_error.push(spreadsheet.row(i))
          when ".xlsx" then
            @array_error.push(spreadsheet.row(i))
          else raise "Unknown file type: #{file.original_filename}"
        end
      end
    end
  end

  def self.check_import_errors
    if @array_error.blank?
      true
    else
      false
      @array_error
    end
  end

  # export to csv and xls
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |delivery_rate|
        csv << delivery_rate.attributes.values_at(*column_names)
      end
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::Csv.new(file.path)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]

  # Check user role
  before_action :check_role_client, only: [:index, :new, :show, :edit, :create, :update, :destroy]
  before_action :check_role_partner, only: [:index, :new, :show, :edit, :create, :update, :destroy]

  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.paginate(page: params[:page])
    respond_to do |format|
      format.html
      # format json for android app
      format.json { render json: @airports }
      format.xml { render xml: @airports }
      # export to csv and xls
      format.csv { send_data @airports.to_csv }
      format.xls { send_data @airports.to_csv(col_sep: "\t") }
    end
  end

  # import CSV rates
  def import_form
    @airports = Airport.all
    respond_to do |format|
      format.html
      # format json for android app
      format.json { render json: @airports }
      format.xml { render xml: @airports }
      # export to csv and xls
      format.csv { send_data @airports.to_csv }
      format.xls { send_data @airports.to_csv(col_sep: "\t") }
    end
  end

  def import
    if params[:file].nil?
      respond_to do |format|
        format.html { flash[:success] = ((t 'notice.file_format_error'))
        redirect_to airports_path }
      end
    else
      case File.extname(params[:file].original_filename)
        when ".csv" then
          Airport.import(params[:file])
          if Airport.check_import_errors == true
            respond_to do |format|
              format.html { flash[:success] = (t 'notice.import_success')
              redirect_to airports_path }
            end
          else
            @error_import = " Rows: "
            Airport.check_import_errors.each_with_index do |product, index|
              @error_import += "#{index} "
            end
            respond_to do |format|
              format.html { flash[:danger] = ((t 'notice.import_error') + @error_import)
              redirect_to airports_path }
            end
          end
        when ".xls", ".xlsx" then
          Airport.import(params[:file])
          if Airport.check_import_errors == true
            respond_to do |format|
              format.html { flash[:success] = (t 'notice.import_success')
              redirect_to airports_path }
            end
          else
            @error_import = " Rows: "
            Airport.check_import_errors.each_with_index do |product, index|
              @error_import += "#{product} "
            end
            respond_to do |format|
              format.html { flash[:danger] = ((t 'notice.import_error') + @error_import)
              redirect_to airports_path }
            end
          end
        else
          respond_to do |format|
            format.html { flash[:success] = ((t 'notice.file_format_error') + "#{params[:file].original_filename}")
            redirect_to airports_path }
          end
      end
    end

  end

  # GET /airports/1
  # GET /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render action: 'show', status: :created, location: @airport }
      else
        format.html { render action: 'new' }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1
  # PATCH/PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url }
      format.json { head :no_content }
    end
  end

  # Check user role
  def check_role_client
    if (current_user && current_user.role == "Client") || (current_user && current_user.role == "OAuth")
      redirect_to root_path
      flash[:danger] = I18n.t 'flash.access_deny_text'
    end
  end

  def check_role_partner
    if (current_user && current_user.role == "Partner") || (current_user && current_user.role == "OAuth")
      redirect_to root_path
      flash[:danger] = I18n.t 'flash.access_deny_text'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(:code, :cc_fips, :name, :lat, :long, :fixed_fare)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<%= form_for(@airport) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% @airport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :cc_fips %><br>
    <%= f.text_field :cc_fips %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :fixed_fare %><br>
    <%= f.text_field :fixed_fare %>
  </div>
  <div class="actions">
    <%= f.submit (t 'button.ok'), class: "btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing airport</h1>

<%= render 'form' %>

<%= link_to (I18n.t 'button.show'), @airport, class: "btn btn-sm btn-primary" %> |
<%= link_to (I18n.t 'button.back'), airports_path, class: "btn btn-sm btn-warning" %>

app/views/airports/import_form.html.erb
<h1 align="center"><%= (I18n.t 'button.import') %> (*.CSV) <%= t ('or') %> (*.XLS) <%= t ('or') %> (*.XLSX)</h1>
<%= form_tag import_airports_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag (I18n.t 'button.import'), class: "btn btn-sm btn-primary" %>
<% end %>

app/views/airports/index.html.erb
<h1 align="center"><%= (t 'airports.airports') %> <span class="badge"><%= @airports.count %></span></h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Cc fips</th>
      <th>Name</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Fixed fare</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airports.each do |airport| %>
      <tr>
        <td><%= airport.code %></td>
        <td><%= airport.cc_fips %></td>
        <td><%= airport.name %></td>
        <td><%= airport.lat %></td>
        <td><%= airport.long %></td>
        <td><%= airport.fixed_fare %></td>
        <td><%= link_to 'Show', airport, class: "btn btn-sm btn-primary" %></td>
        <td><%= link_to 'Edit', edit_airport_path(airport), class: "btn btn-sm btn-warning" %></td>
        <td><%= link_to 'Destroy', airport, method: :delete, data: {confirm: (t 'operations_confirmation.confirm')}, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airport', new_airport_path, class: "btn btn-sm btn-primary" %>

<p>
  Download:
  <%= link_to "CSV", airports_path(format: "csv") %> |
  <%= link_to "Excel", airports_path(format: "xls") %>
    <%= t ('or') %>
  <%= (I18n.t 'button.import') %> :
  <%= link_to "*.CSV, *.XLS, *.XLSX", import_airports_form_path, class: "btn btn-sm btn-default" %>
</p>

app/views/airports/new.html.erb
<h1>New airport</h1>

<%= render 'form' %>

<%= link_to (I18n.t 'button.back'), airports_path, class: "btn btn-sm btn-warning" %>

app/views/airports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @airport.code %>
</p>

<p>
  <strong>Cc fips:</strong>
  <%= @airport.cc_fips %>
</p>

<p>
  <strong>Name:</strong>
  <%= @airport.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @airport.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @airport.long %>
</p>

<p>
  <strong>Fixed fare:</strong>
  <%= @airport.fixed_fare %>
</p>

<%= link_to (I18n.t 'button.edit'), edit_airport_path(@airport), class: "btn btn-sm btn-primary" %> |
<%= link_to (I18n.t 'button.back'), airports_path, class: "btn btn-sm btn-warning" %>